### ISSUE TITLE
I cannot get rszz.yml working with the sample test below

### ISSUE THREAD

**Issue by johnxu21** [grosa1/pyszz#1]
[
  {
    "fix_commit_hash": "e94a2abdb98ed52eb37e7ee3bc1aab843ccb4478",
    "repo_name": "nakagami/CyMySQL"
  }
]

Other configuration files are successful but rszz.yml

**Comment by johnxu21** [comment]
all the conf files fail with the following input file

[
    {
        "fix_commit_hash": "1df9b5e5ad3a0e938bbdeaff25f27413832c5e90",
        "repo_name": "Electron-Cash/Electron-Cash"
    }
]

Traceback (most recent call last):
  File "/Users/businge/Documents/00Masters_UA/Poedja/pyszz/main.py", line 148, in <module>
    main(input_json, out_json, conf, repos_dir)
  File "/Users/businge/Documents/00Masters_UA/Poedja/pyszz/main.py", line 73, in main
    imp_files = r_szz.get_impacted_files(fix_commit_hash=fix_commit, file_ext_to_parse=conf.get('file_ext_to_parse'), only_deleted_lines=conf.get('only_deleted_lines', True))
  File "/Users/businge/Documents/00Masters_UA/Poedja/pyszz/szz/core/abstract_szz.py", line 118, in get_impacted_files
    fix_commit = PyDrillerGitRepo(self.repository_path).get_commit(fix_commit_hash)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydriller/git_repository.py", line 143, in get_commit
    gp_commit = self.repo.commit(commit_id)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/repo/base.py", line 480, in commit
    return self.rev_parse(str(rev) + "^0")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/repo/fun.py", line 213, in rev_parse
    obj = name_to_object(repo, rev[:start])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/repo/fun.py", line 150, in name_to_object
    return Object.new_from_sha(repo, hex_to_bin(hexsha))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/objects/base.py", line 64, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/db.py", line 37, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(sha))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/cmd.py", line 1068, in get_object_header
    return self.__get_object_header(cmd, ref)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/cmd.py", line 1057, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/cmd.py", line 1021, in _parse_object_header
    raise ValueError("SHA %s could not be resolved, git returned: %r" % (tokens[0], header_line.strip()))
ValueError: SHA b'1df9b5e5ad3a0e938bbdeaff25f27413832c5e90' could not be resolved, git returned: b'1df9b5e5ad3a0e938bbdeaff25f27413832c5e90 missing'

**Comment by grosa1** [comment]
Hi, I have manually checked the two issues.

> [
> {
> "fix_commit_hash": "e94a2abdb98ed52eb37e7ee3bc1aab843ccb4478",
> "repo_name": "nakagami/CyMySQL"
> }
> ]
> 
> Other configuration files are successful but rszz.yml

1. Maybe you need to edit the configuration file disabling `issue_date_filter`.



> all the conf files fail with the following input file
> 
> [
> {
> "fix_commit_hash": "1df9b5e5ad3a0e938bbdeaff25f27413832c5e90",
> "repo_name": "Electron-Cash/Electron-Cash"
> }
> ]
> 
> Traceback (most recent call last):
> File "/Users/businge/Documents/00Masters_UA/Poedja/pyszz/main.py", line 148, in
> main(input_json, out_json, conf, repos_dir)
> File "/Users/businge/Documents/00Masters_UA/Poedja/pyszz/main.py", line 73, in main
> imp_files = r_szz.get_impacted_files(fix_commit_hash=fix_commit, file_ext_to_parse=conf.get('file_ext_to_parse'), only_deleted_lines=conf.get('only_deleted_lines', True))
> File "/Users/businge/Documents/00Masters_UA/Poedja/pyszz/szz/core/abstract_szz.py", line 118, in get_impacted_files
> fix_commit = PyDrillerGitRepo(self.repository_path).get_commit(fix_commit_hash)
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydriller/git_repository.py", line 143, in get_commit
> gp_commit = self.repo.commit(commit_id)
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/repo/base.py", line 480, in commit
> return self.rev_parse(str(rev) + "^0")
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/repo/fun.py", line 213, in rev_parse
> obj = name_to_object(repo, rev[:start])
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/repo/fun.py", line 150, in name_to_object
> return Object.new_from_sha(repo, hex_to_bin(hexsha))
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/objects/base.py", line 64, in new_from_sha
> oinfo = repo.odb.info(sha1)
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/db.py", line 37, in info
> hexsha, typename, size = self._git.get_object_header(bin_to_hex(sha))
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/cmd.py", line 1068, in get_object_header
> return self.__get_object_header(cmd, ref)
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/cmd.py", line 1057, in __get_object_header
> return self._parse_object_header(cmd.stdout.readline())
> File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/git/cmd.py", line 1021, in _parse_object_header
> raise ValueError("SHA %s could not be resolved, git returned: %r" % (tokens[0], header_line.strip()))
> ValueError: SHA b'1df9b5e5ad3a0e938bbdeaff25f27413832c5e90' could not be resolved, git returned: b'1df9b5e5ad3a0e938bbdeaff25f27413832c5e90 missing'

2.  The provided commit seems to not exist in the repository tree. However, you can check it using git CLI.

**Comment by johnxu21** [comment]
Thanks @grosa1 this helps 👍
