### ISSUE TITLE
Incomplete Docker image

### ISSUE THREAD

**Issue by Maes95** [grosa1/pyszz#2]
I thank the authors for their work in providing the implementations of the SZZ variants.

When using the Docker image that is generated through the provided Dockerfile, I have detected that it is incomplete and does not allow to run `raszz`. 

- This algorithm requires the Options class (not added by the Dockerfile). The error is even more confusing, as some default Python class is used. The "tools/" folder is also required and is not available. The executable tools/RefactoringMiner-2.0/bin/RefactoringMiner does not have execute permissions

*Quick-fix*:

```Dockerfile
COPY tools tools
COPY options.py .
RUN chmod +x tools/RefactoringMiner-2.0/bin/RefactoringMiner
```

- The algorithm requires the execution of a JAR (RefactoringMiner) and therefore requires Java, which is not installed in the image.

*Quick-fix* (_I select Java 11, that works for some examples_)
```Dockerfile
RUN echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list && \ 
  apt-get update && apt-get upgrade -y --no-install-recommends && \
  apt-get -y install openjdk-11-jre-headless && \
  apt-get install -y --no-install-recommends wget libarchive13 libcurl4 libxml2 python-magic && \
  apt-get -t buster-backports install -y --no-install-recommends git && \
  rm -rf /var/lib/apt/lists/*
```

I hope this helps you to improve your tool

**Comment by grosa1** [comment]
Thank you very much. I will release the fix soon.
