### ISSUE TITLE
Question regarding the implementation of AGSZZ

### ISSUE THREAD

**Issue by nayeawon** [grosa1/pyszz#4]
Hello😊
First off, thanks for the amazing work on pyszz

I am currently having hard time understanding on just one part of your implementation on the AGSZZ. 
In `szz/ag_szz.py`,the function `_ag_annotate` as below.

<img width="546" alt="Screen Shot 2022-07-04 at 12 13 15 PM" src="https://user-images.githubusercontent.com/80326384/177075218-a45162c9-c595-45a2-9e99-ab82572a1a40.png">

The set `blame_data` which is initialized in line number 37 is being updated in every iteration. Consequently, the result would only show the blamed data of the last `imp_file` listed in `impacted_files`.

But as far as I understood from your paper, AGSZZ has to output blamed data for each file and for each line.

Could you please help me if there was something I have missed?

Thank you!

**Comment by nayeawon** [comment]
I am currently using the setting of #5
I am not sure if this could be a fix for the problem.

**Comment by grosa1** [comment]
fixed by #5
