### ISSUE TITLE
RASZZ continuously runs reblame on a commit, how to solve this problem?

### ISSUE THREAD

**Issue by Owner-MR** [grosa1/pyszz#6]
Hello,
Thank you very much for the szz code.
When I run RASZZ, a commit keeps running the reblame module many times in a loop.
![1](https://user-images.githubusercontent.com/57560083/190894194-8c4b64d8-2a2c-4ab3-a3ce-2a0059a12062.png)
![2](https://user-images.githubusercontent.com/57560083/190894280-4158bc6b-9a8a-42ab-b188-702db053c6ba.png)

**Comment by grosa1** [comment]
Hi,
in order to replicate the issue, can you give me the input provided to raszz, please?

**Comment by Owner-MR** [comment]
> Hi, in order to replicate the issue, can you give me the input provided to raszz, please?

this is my input file:
![3](https://user-images.githubusercontent.com/57560083/190943164-0b156ce2-96d7-45cb-9246-5e4017e8f3c4.png)

**Comment by grosa1** [comment]
The field `"repo_name"` must contain the repository owner and repository name, e.g. `"repo_name": "ownername/afwall"`.
Moreover, I need the input and the command you executed which lead to the issue. You sent me a screenshot, please send me the file directly, or else provide the commit and repository for which you encounter the issue. You can send them to me privately by email.

**Comment by Owner-MR** [comment]
Hello,

  Thank you for your reply, I can successfully run bszz with the current file, but RASZZ running this commit has an infinite loop problem:

[
  {
        "fix_commit_hash": "c230c5f3e06c3d0c017873774c9181227a7f859a",
        "repo_name": "afwall"
  }
]
 

  In order to solve this problem, I set up constraints, if the INFO information generated by reblaming is consistent with the last time, it will be skipped. I don't know if doing this will affect the results, but it works successfully so far.

The repo-url of afwall： https://github.com/ukanth/afwall.git
And this is my input json file:
[afwall.zip](https://github.com/grosa1/pyszz/files/9662688/afwall.zip)

**Comment by grosa1** [comment]
Hello,
sorry for the late response. Your fix seems to be ok.
I still can not replicate the issue. In my case, RA-SZZ works without loops also using your example.
In any case, I will update RA-SZZ with some minor improvements if you want to make another test.
Please remember to replace `"repo_name": "afwall"` with `"repo_name": "ukanth/afwall"`

**Comment by Owner-MR** [comment]
Thank you again for your help!
